org: nicopret
app: dos-matcher
service: hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

plugins:
  - serverless-import-apigateway

custom:
  importApiGateway:
    name: podproduce

provider:
  deploymentBucket:
    name: dosmatcher2
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
    events:
      - http:
          path: hello/{name}
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "name" : "$input.params(''name'')" }'

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dosMatcherTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
