org: nicopret
app: dos-matcher
service: hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

plugins:
  - serverless-import-apigateway

custom:
  bucketName: dosmatcher2
  importApiGateway:
    name: podproduce

provider:
  deploymentBucket:
    name: ${self:custom.bucketName}
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource: "arn:aws:s3:::dosmatcher2"
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
          Resource: "arn:aws:s3:::dosmatcher2"
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
