org: nicopret
app: dos-matcher
service: hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

provider:
  deploymentBucket:
    name: dosmatcher2
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
