service: serverless-hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

provider:
  deploymentBucket:
    name: dosmatcher.serverless
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  name: aws
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
