org: nicopret
app: dos-matcher
service: hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

plugins:
  - serverless-import-apigateway

custom:
  bucketName: dosmatcher2
  importApiGateway:
    name: podproduce

provider:
  deploymentBucket:
    name: ${self:custom.bucketName}
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
