org: nicopret
app: dos-matcher
service: hello
frameworkVersion: '3'

package:
  patterns:
  - '!coverage/**'
  - '!.circleci/**'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  test:
    handler: index.handler
